name: Front-dev build & push docker image to ghcr and deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: TopazKang
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/topazkang/fe-dev:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/topazkang/fe-dev:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.ARK_DEPLOY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE_DEV }}" > deploy/back/.env
            echo "${{ secrets.GHCR_TOKEN }}" | sudo docker login ghcr.io -u ${{ secrets.GIT_USER }} --password-stdin
            cd deploy/back
            sudo docker-compose -f docker-compose.front.yaml down
            sudo docker-compose -f docker-compose.front.yaml pull
            sudo docker-compose -f docker-compose.front.yaml up
